language: php
php:
  - 7.0
  - 7.1
  - 7.2
before_install:
  - export PATH="$PATH:$(composer global config bin-dir --absolute)"
  - composer global require "squizlabs/php_codesniffer=3.*"
  - phpenv rehash
script:
  - find src -type f -name '*.php' |xargs -I file php -l file
  - phpcs -p --extensions=php --standard="PSR2" src
